import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const UnauthorizedPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>QnA App - Unauthorized</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl font-bold text-white sm:text-[4rem]">
            Unauthorized
          </h1>
          <div className="grid">
            <h2 className="text-center text-xl text-white sm:text-[1.5rem]">
              You need to login to see this page
            </h2>
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="flex flex-col items-center justify-center gap-4">
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => void signIn(undefined, { callbackUrl: "/" })}
              >
                Login
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default UnauthorizedPage;
